### ISSUE TITLE
Item Tagging

### ISSUE THREAD

**Issue by CodeNeedsCoffee** [ExplodedCode/Giftamizer#21]
![image](https://user-images.githubusercontent.com/16927633/141672019-fe057013-904f-460e-81e7-660694f83c3e.png)

This item was on two lists but the buyer couldn't tell. @EvanTrow is it designed to be this way?

**Comment by EvanTrow** [comment]
Lists are primarily for organization the items you have.

**Comment by EvanTrow** [comment]
Child lists are for displaying items as a separate person to the group.

**Comment by CodeNeedsCoffee** [comment]
But what if I want to add tags? Like "Item's I Need" vs "Item's I Want", or do you not think a custom tagging system is needed? 🤔

**Comment by EvanTrow** [comment]
I think descriptions or custom fields can handle this... 
Also planning on adding a most wanted checkbox/switch
