### ISSUE TITLE
ux: how does item state change?

### ISSUE THREAD

**Issue by danfred360** [ExplodedCode/Giftamizer#47]
It's not really clear how the state of an item in a list changes. See video on imgur [here](https://imgur.com/a/ZBAKdNP). It seems like there's a user experience improvement to be made here.

![image](https://github.com/ExplodedCode/Giftamizer/assets/11318300/7c88b88a-98e7-45f5-837c-f44e9e383293)

![image](https://github.com/ExplodedCode/Giftamizer/assets/11318300/a6a36c67-2565-4b1b-8a01-f7865b711c26)

**Comment by EvanTrow** [comment]
Added tool tips and description in user tour.
