### ISSUE TITLE
URL Metadata - Unable to get name, description, and image of URL

### ISSUE THREAD

**Issue by NeverEndingCode** [ExplodedCode/Giftamizer#52]
POST - https://giftamizer.com/functions/v1/url-metadata

URL Examples:
https://hollisterco.app.link/?$deeplink_path=product%2Fcollection%2F530181%2Fkic%2FKIC%5F519%2D3041%2D0123%2D112%3FshortSku%3D655240961&$desktop_url=https%3A%2F%2Fwww.hollisterco.com%2Fshop%2Fus%2Fgilly%2Dhicks%2Fp%2Fgilly%2Dhicks%2Dactive%2Dwide%2Dleg%2Dcargo%2Dsweatpants%2D53679841%3Fofp%3Dtrue&$og_image_url=https%3A%2F%2Fimg.hollisterco.com%2Fis%2Fimage%2Fanf%2FKIC%5F519%2D3041%2D0123%2D112%5Fmodel1%3Fpolicy%3Dproduct%2Dsmall&$og_title=Gilly%20Hicks%20Active%20Wide%2DLeg%20Cargo%20Sweatpants
-->This deeplink actually goes to:
https://www.hollisterco.com/shop/us/gilly-hicks/p/gilly-hicks-active-wide-leg-cargo-sweatpants-53679841?ofp=true&%24deeplink_path=product%2Fcollection%2F530181%2Fkic%2FKIC_519-3041-0123-112%3FshortSku%3D655240961&%24og_image_url=https%3A%2F%2Fimg.hollisterco.com%2Fis%2Fimage%2Fanf%2FKIC_519-3041-0123-112_model1%3Fpolicy%3Dproduct-small&%24og_title=Gilly%20Hicks%20Active%20Wide-Leg%20Cargo%20Sweatpants&_branch_match_id=1237127457960147326&_branch_referrer=H4sIAAAAAAAAA3WQwWrDMAyGnya7BKdxnHRtoYzS0W1stx52DMZRHRMnNrGy0LefHMrYoAMjWTLS%2F%2F1uEX3YrVats9YEhFG5THqfWTN0q6ekKBsAH4vaS2z3fnTNpDApTooGQKFxAxWVyPmG06UziuL727Gu%2BJaJvOQs54VgnBeJOIXWjXjupkQ8r6uqKPPtmj8sGqFD5%2BtptPs2AiXiQGvozPOc%2FUZTrqcu7fGUpkBBG2uvrDWqi5X%2F22GSCL%2BAzaYBZkEzJUftWJhBopcDBlaJ9eN2U3KicxdPYDhOEJmcrk0vNdyBMr2%2BA2XC8kQjlOVw%2Be8f6t41YKOgd9aoK2nefpWFXlp7E0eDFvYv0Uv6Gr2kh8VL%2Bhm9fIBOj9FLev7x8g0m84V0ywEAAA%3D%3D

Another example:
https://www.amazon.com/Govee-Electric-Gooseneck-Temperature-Stainless/dp/B09TSKDKCL/?_encoding=UTF8&pd_rd_w=IxuHq&content-id=amzn1.sym.1d891a60-9b32-46d5-a62d-58dfad00a1c3&pf_rd_p=1d891a60-9b32-46d5-a62d-58dfad00a1c3&pf_rd_r=7D8JSZ0R4HM5DQDM64HY&pd_rd_wg=9lXmc&pd_rd_r=97a64380-05ce-4fbd-b225-64c7caf3a58f&ref_=pd_gw_deals_4s_t1

**Comment by EvanTrow** [comment]
resolved
