### ISSUE TITLE
Snow Only Fills Screen On Load - Breaks when Scrolling

### ISSUE THREAD

**Issue by CodeNeedsCoffee** [ExplodedCode/Giftamizer#53]
The snow only fills the available monitor size when it loads. After scrolling, the snow doesn't continue to fill the newly available space.

Red area has snow where the rest is missing due to scrolling down the page:
![image](https://github.com/ExplodedCode/Giftamizer/assets/16927633/4be2b180-77a2-4376-ba52-84766dac978c)

**Comment by EvanTrow** [comment]
Changed div position from absolute to fixed.
